"""Add phone field and make email optional

Revision ID: a894d4ad1aad
Revises: c5b6df233995
Create Date: 2026-02-01 16:32:22.750980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a894d4ad1aad'
down_revision: Union[str, None] = 'c5b6df233995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add phone column as nullable
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    
    # Update existing users with phone based on email (temporary placeholder)
    op.execute("UPDATE \"user\" SET phone = '+998' || SUBSTRING(email, 1, 9) WHERE phone IS NULL")
    
    # Now make phone non-nullable
    op.alter_column('user', 'phone', nullable=False)
    
    # Make email nullable
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
