"""remove_full_name_make_names_required

Revision ID: b7094dda36fe
Revises: decdec26a909
Create Date: 2026-02-01 19:36:42.520959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7094dda36fe'
down_revision: Union[str, None] = 'decdec26a909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # First, populate last_name and first_name from full_name for existing records
    op.execute("""
        UPDATE patient 
        SET 
            last_name = COALESCE(last_name, split_part(full_name, ' ', 1)),
            first_name = COALESCE(first_name, split_part(full_name, ' ', 2)),
            middle_name = COALESCE(middle_name, 
                CASE WHEN array_length(string_to_array(full_name, ' '), 1) > 2 
                THEN split_part(full_name, ' ', 3) 
                ELSE NULL END
            )
        WHERE last_name IS NULL OR first_name IS NULL
    """)
    
    # Set default values for any remaining nulls
    op.execute("UPDATE patient SET last_name = 'Unknown' WHERE last_name IS NULL OR last_name = ''")
    op.execute("UPDATE patient SET first_name = 'Unknown' WHERE first_name IS NULL OR first_name = ''")
    
    # Now make columns NOT NULL
    op.alter_column('patient', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('patient', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_patient_full_name'), table_name='patient')
    op.create_index(op.f('ix_patient_last_name'), 'patient', ['last_name'], unique=False)
    op.drop_column('patient', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_patient_last_name'), table_name='patient')
    op.create_index(op.f('ix_patient_full_name'), 'patient', ['full_name'], unique=False)
    op.alter_column('patient', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('patient', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
