"""Add patient examination and template models

Revision ID: c5b6df233995
Revises: 0d5161899d69
Create Date: 2026-02-01 14:26:27.433779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5b6df233995'
down_revision: Union[str, None] = '0d5161899d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_full_name'), 'patient', ['full_name'], unique=False)
    op.create_index(op.f('ix_patient_is_deleted'), 'patient', ['is_deleted'], unique=False)
    op.create_table('template',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conclusion_templates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendation_templates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('print_template', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_category'), 'template', ['category'], unique=False)
    op.create_index(op.f('ix_template_code'), 'template', ['code'], unique=True)
    op.create_index(op.f('ix_template_is_deleted'), 'template', ['is_deleted'], unique=False)
    op.create_table('examination',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('examination_date', sa.Date(), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('examination_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examination_doctor_id'), 'examination', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_examination_examination_date'), 'examination', ['examination_date'], unique=False)
    op.create_index(op.f('ix_examination_is_deleted'), 'examination', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_examination_patient_id'), 'examination', ['patient_id'], unique=False)
    op.create_index(op.f('ix_examination_template_type'), 'examination', ['template_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examination_template_type'), table_name='examination')
    op.drop_index(op.f('ix_examination_patient_id'), table_name='examination')
    op.drop_index(op.f('ix_examination_is_deleted'), table_name='examination')
    op.drop_index(op.f('ix_examination_examination_date'), table_name='examination')
    op.drop_index(op.f('ix_examination_doctor_id'), table_name='examination')
    op.drop_table('examination')
    op.drop_index(op.f('ix_template_is_deleted'), table_name='template')
    op.drop_index(op.f('ix_template_code'), table_name='template')
    op.drop_index(op.f('ix_template_category'), table_name='template')
    op.drop_table('template')
    op.drop_index(op.f('ix_patient_is_deleted'), table_name='patient')
    op.drop_index(op.f('ix_patient_full_name'), table_name='patient')
    op.drop_table('patient')
    # ### end Alembic commands ###
