"""add_separate_name_fields_to_patient

Revision ID: decdec26a909
Revises: a894d4ad1aad
Create Date: 2026-02-01 19:30:43.789268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decdec26a909'
down_revision: Union[str, None] = 'a894d4ad1aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('patient', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('patient', sa.Column('middle_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'middle_name')
    op.drop_column('patient', 'first_name')
    op.drop_column('patient', 'last_name')
    # ### end Alembic commands ###
