/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPatientsRouteImport } from './routes/_layout/patients'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutExaminationsIndexRouteImport } from './routes/_layout/examinations/index'
import { Route as LayoutExaminationsNewRouteImport } from './routes/_layout/examinations/new'
import { Route as LayoutExaminationsIdRouteImport } from './routes/_layout/examinations/$id'
import { Route as LayoutExaminationsEditIdRouteImport } from './routes/_layout/examinations/edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatientsRoute = LayoutPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExaminationsIndexRoute = LayoutExaminationsIndexRouteImport.update({
  id: '/examinations/',
  path: '/examinations/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExaminationsNewRoute = LayoutExaminationsNewRouteImport.update({
  id: '/examinations/new',
  path: '/examinations/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExaminationsIdRoute = LayoutExaminationsIdRouteImport.update({
  id: '/examinations/$id',
  path: '/examinations/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExaminationsEditIdRoute =
  LayoutExaminationsEditIdRouteImport.update({
    id: '/examinations/edit/$id',
    path: '/examinations/edit/$id',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/patients': typeof LayoutPatientsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/examinations/$id': typeof LayoutExaminationsIdRoute
  '/examinations/new': typeof LayoutExaminationsNewRoute
  '/examinations': typeof LayoutExaminationsIndexRoute
  '/examinations/edit/$id': typeof LayoutExaminationsEditIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/patients': typeof LayoutPatientsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/examinations/$id': typeof LayoutExaminationsIdRoute
  '/examinations/new': typeof LayoutExaminationsNewRoute
  '/examinations': typeof LayoutExaminationsIndexRoute
  '/examinations/edit/$id': typeof LayoutExaminationsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/patients': typeof LayoutPatientsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/examinations/$id': typeof LayoutExaminationsIdRoute
  '/_layout/examinations/new': typeof LayoutExaminationsNewRoute
  '/_layout/examinations/': typeof LayoutExaminationsIndexRoute
  '/_layout/examinations/edit/$id': typeof LayoutExaminationsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/admin'
    | '/items'
    | '/patients'
    | '/settings'
    | '/'
    | '/examinations/$id'
    | '/examinations/new'
    | '/examinations'
    | '/examinations/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/items'
    | '/patients'
    | '/settings'
    | '/'
    | '/examinations/$id'
    | '/examinations/new'
    | '/examinations'
    | '/examinations/edit/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/patients'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/examinations/$id'
    | '/_layout/examinations/new'
    | '/_layout/examinations/'
    | '/_layout/examinations/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients': {
      id: '/_layout/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof LayoutPatientsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/examinations/': {
      id: '/_layout/examinations/'
      path: '/examinations'
      fullPath: '/examinations'
      preLoaderRoute: typeof LayoutExaminationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/examinations/new': {
      id: '/_layout/examinations/new'
      path: '/examinations/new'
      fullPath: '/examinations/new'
      preLoaderRoute: typeof LayoutExaminationsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/examinations/$id': {
      id: '/_layout/examinations/$id'
      path: '/examinations/$id'
      fullPath: '/examinations/$id'
      preLoaderRoute: typeof LayoutExaminationsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/examinations/edit/$id': {
      id: '/_layout/examinations/edit/$id'
      path: '/examinations/edit/$id'
      fullPath: '/examinations/edit/$id'
      preLoaderRoute: typeof LayoutExaminationsEditIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPatientsRoute: typeof LayoutPatientsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutExaminationsIdRoute: typeof LayoutExaminationsIdRoute
  LayoutExaminationsNewRoute: typeof LayoutExaminationsNewRoute
  LayoutExaminationsIndexRoute: typeof LayoutExaminationsIndexRoute
  LayoutExaminationsEditIdRoute: typeof LayoutExaminationsEditIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPatientsRoute: LayoutPatientsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutExaminationsIdRoute: LayoutExaminationsIdRoute,
  LayoutExaminationsNewRoute: LayoutExaminationsNewRoute,
  LayoutExaminationsIndexRoute: LayoutExaminationsIndexRoute,
  LayoutExaminationsEditIdRoute: LayoutExaminationsEditIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
