/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPatientsRouteImport } from './routes/_layout/patients'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutExaminationsRouteImport } from './routes/_layout/examinations'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutExaminationsNewRouteImport } from './routes/_layout/examinations/new'
import { Route as LayoutExaminationsIdRouteImport } from './routes/_layout/examinations/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatientsRoute = LayoutPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExaminationsRoute = LayoutExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExaminationsNewRoute = LayoutExaminationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutExaminationsRoute,
} as any)
const LayoutExaminationsIdRoute = LayoutExaminationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutExaminationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/examinations': typeof LayoutExaminationsRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/patients': typeof LayoutPatientsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/examinations/$id': typeof LayoutExaminationsIdRoute
  '/examinations/new': typeof LayoutExaminationsNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/examinations': typeof LayoutExaminationsRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/patients': typeof LayoutPatientsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/examinations/$id': typeof LayoutExaminationsIdRoute
  '/examinations/new': typeof LayoutExaminationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/examinations': typeof LayoutExaminationsRouteWithChildren
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/patients': typeof LayoutPatientsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/examinations/$id': typeof LayoutExaminationsIdRoute
  '/_layout/examinations/new': typeof LayoutExaminationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/admin'
    | '/examinations'
    | '/items'
    | '/patients'
    | '/settings'
    | '/'
    | '/examinations/$id'
    | '/examinations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/examinations'
    | '/items'
    | '/patients'
    | '/settings'
    | '/'
    | '/examinations/$id'
    | '/examinations/new'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/admin'
    | '/_layout/examinations'
    | '/_layout/items'
    | '/_layout/patients'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/examinations/$id'
    | '/_layout/examinations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients': {
      id: '/_layout/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof LayoutPatientsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/examinations': {
      id: '/_layout/examinations'
      path: '/examinations'
      fullPath: '/examinations'
      preLoaderRoute: typeof LayoutExaminationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/examinations/new': {
      id: '/_layout/examinations/new'
      path: '/new'
      fullPath: '/examinations/new'
      preLoaderRoute: typeof LayoutExaminationsNewRouteImport
      parentRoute: typeof LayoutExaminationsRoute
    }
    '/_layout/examinations/$id': {
      id: '/_layout/examinations/$id'
      path: '/$id'
      fullPath: '/examinations/$id'
      preLoaderRoute: typeof LayoutExaminationsIdRouteImport
      parentRoute: typeof LayoutExaminationsRoute
    }
  }
}

interface LayoutExaminationsRouteChildren {
  LayoutExaminationsIdRoute: typeof LayoutExaminationsIdRoute
  LayoutExaminationsNewRoute: typeof LayoutExaminationsNewRoute
}

const LayoutExaminationsRouteChildren: LayoutExaminationsRouteChildren = {
  LayoutExaminationsIdRoute: LayoutExaminationsIdRoute,
  LayoutExaminationsNewRoute: LayoutExaminationsNewRoute,
}

const LayoutExaminationsRouteWithChildren =
  LayoutExaminationsRoute._addFileChildren(LayoutExaminationsRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutExaminationsRoute: typeof LayoutExaminationsRouteWithChildren
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPatientsRoute: typeof LayoutPatientsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutExaminationsRoute: LayoutExaminationsRouteWithChildren,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPatientsRoute: LayoutPatientsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
