// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_access_token'
} as const;

export const ExaminationCreateSchema = {
    properties: {
        patient_id: {
            type: 'integer',
            title: 'Patient Id',
            description: 'Bemor ID'
        },
        examination_date: {
            type: 'string',
            format: 'date',
            title: 'Examination Date',
            description: 'Tekshiruv sanasi'
        },
        template_type: {
            type: 'string',
            title: 'Template Type',
            description: 'Shablon turi'
        },
        examination_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Examination Data',
            description: "Tekshiruv ma'lumotlari (JSONB)"
        },
        conclusion: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Conclusion',
            description: 'Xulosa / ЗАКЛЮЧЕНИЕ'
        },
        recommendations: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recommendations',
            description: 'Tavsiyalar / РЕКОМЕНДАЦИИ'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Ichki izohlar'
        },
        status: {
            type: 'string',
            pattern: '^(draft|completed|printed)$',
            title: 'Status',
            description: 'Holat',
            default: 'draft'
        }
    },
    type: 'object',
    required: ['patient_id', 'template_type'],
    title: 'ExaminationCreate',
    description: 'Yangi tekshiruv yaratish'
} as const;

export const ExaminationListSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        patient_id: {
            type: 'integer',
            title: 'Patient Id'
        },
        patient_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Patient Name'
        },
        examination_date: {
            type: 'string',
            format: 'date',
            title: 'Examination Date'
        },
        template_type: {
            type: 'string',
            title: 'Template Type'
        },
        template_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Template Name'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'patient_id', 'examination_date', 'template_type', 'status', 'created_at'],
    title: 'ExaminationList',
    description: "Tekshiruvlar ro'yxati"
} as const;

export const ExaminationReadSchema = {
    properties: {
        patient_id: {
            type: 'integer',
            title: 'Patient Id',
            description: 'Bemor ID'
        },
        examination_date: {
            type: 'string',
            format: 'date',
            title: 'Examination Date',
            description: 'Tekshiruv sanasi'
        },
        template_type: {
            type: 'string',
            title: 'Template Type',
            description: 'Shablon turi'
        },
        examination_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Examination Data',
            description: "Tekshiruv ma'lumotlari (JSONB)"
        },
        conclusion: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Conclusion',
            description: 'Xulosa / ЗАКЛЮЧЕНИЕ'
        },
        recommendations: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recommendations',
            description: 'Tavsiyalar / РЕКОМЕНДАЦИИ'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Ichki izohlar'
        },
        status: {
            type: 'string',
            pattern: '^(draft|completed|printed)$',
            title: 'Status',
            description: 'Holat',
            default: 'draft'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        doctor_id: {
            type: 'integer',
            title: 'Doctor Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        patient_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Patient Name'
        },
        doctor_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doctor Name'
        },
        template_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Template Name'
        }
    },
    type: 'object',
    required: ['patient_id', 'template_type', 'id', 'doctor_id', 'created_at'],
    title: 'ExaminationRead',
    description: "Tekshiruv ma'lumotlarini o'qish"
} as const;

export const ExaminationUpdateSchema = {
    properties: {
        examination_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Examination Date'
        },
        examination_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Examination Data'
        },
        conclusion: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Conclusion'
        },
        recommendations: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recommendations'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(draft|completed|printed)$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        }
    },
    type: 'object',
    title: 'ExaminationUpdate',
    description: "Tekshiruv ma'lumotlarini yangilash"
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthCheckSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        environment: {
            type: 'string',
            title: 'Environment'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        timestamp: {
            type: 'string',
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: ['status', 'environment', 'version', 'timestamp'],
    title: 'HealthCheck'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        created_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        owner_id: {
            type: 'integer',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const JobSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'Job'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: 'Generic message response schema'
} as const;

export const PaginatedResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserRead'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PaginatedResponse'
} as const;

export const PatientCreateSchema = {
    properties: {
        last_name: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Last Name',
            description: 'Familiya'
        },
        first_name: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'First Name',
            description: 'Ism'
        },
        middle_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Middle Name',
            description: 'Otasining ismi / Sharifi'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date',
            description: "Tug'ilgan sana"
        },
        gender: {
            type: 'string',
            pattern: '^(male|female)$',
            title: 'Gender',
            description: 'Jins: male/female'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone',
            description: 'Telefon raqami'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address',
            description: 'Manzil'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Izohlar'
        }
    },
    type: 'object',
    required: ['last_name', 'first_name', 'gender'],
    title: 'PatientCreate',
    description: 'Yangi bemor yaratish'
} as const;

export const PatientListSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        middle_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Middle Name'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date'
        },
        gender: {
            type: 'string',
            title: 'Gender'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        examination_count: {
            type: 'integer',
            title: 'Examination Count',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'last_name', 'first_name', 'gender', 'created_at'],
    title: 'PatientList',
    description: "Bemorlar ro'yxati"
} as const;

export const PatientReadSchema = {
    properties: {
        last_name: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Last Name',
            description: 'Familiya'
        },
        first_name: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'First Name',
            description: 'Ism'
        },
        middle_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Middle Name',
            description: 'Otasining ismi / Sharifi'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date',
            description: "Tug'ilgan sana"
        },
        gender: {
            type: 'string',
            pattern: '^(male|female)$',
            title: 'Gender',
            description: 'Jins: male/female'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone',
            description: 'Telefon raqami'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address',
            description: 'Manzil'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Izohlar'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        examination_count: {
            type: 'integer',
            title: 'Examination Count',
            default: 0
        }
    },
    type: 'object',
    required: ['last_name', 'first_name', 'gender', 'id', 'created_at'],
    title: 'PatientRead',
    description: "Bemor ma'lumotlarini o'qish"
} as const;

export const PatientUpdateSchema = {
    properties: {
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        middle_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Middle Name'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date'
        },
        gender: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(male|female)$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gender'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'PatientUpdate',
    description: "Bemor ma'lumotlarini yangilash"
} as const;

export const ReadyCheckSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        environment: {
            type: 'string',
            title: 'Environment'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        app: {
            type: 'string',
            title: 'App'
        },
        database: {
            type: 'string',
            title: 'Database'
        },
        redis: {
            type: 'string',
            title: 'Redis'
        },
        timestamp: {
            type: 'string',
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: ['status', 'environment', 'version', 'app', 'database', 'redis', 'timestamp'],
    title: 'ReadyCheck'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type'
        }
    },
    type: 'object',
    required: ['access_token', 'token_type'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        first_name: {
            type: 'string',
            maxLength: 50,
            minLength: 2,
            title: 'First Name',
            examples: ['Aziz']
        },
        last_name: {
            type: 'string',
            maxLength: 50,
            minLength: 2,
            title: 'Last Name',
            examples: ['Karimov']
        },
        middle_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Middle Name',
            examples: ['Toshmatovich']
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20,
                    minLength: 2,
                    pattern: '^[a-z0-9]+$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username',
            examples: ['userson']
        },
        phone: {
            type: 'string',
            maxLength: 20,
            minLength: 9,
            title: 'Phone',
            examples: ['+998901234567']
        },
        password: {
            type: 'string',
            pattern: '^.{8,}|[0-9]+|[A-Z]+|[a-z]+|[^a-zA-Z0-9]+$',
            title: 'Password',
            examples: ['Str1ngst!']
        },
        confirm_password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Confirm Password'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'phone', 'password'],
    title: 'UserCreate'
} as const;

export const UserReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id',
            examples: ['1']
        },
        first_name: {
            type: 'string',
            maxLength: 50,
            minLength: 2,
            title: 'First Name',
            examples: ['Aziz']
        },
        last_name: {
            type: 'string',
            maxLength: 50,
            minLength: 2,
            title: 'Last Name',
            examples: ['Karimov']
        },
        middle_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Middle Name',
            examples: ['Toshmatovich']
        },
        username: {
            type: 'string',
            maxLength: 20,
            minLength: 2,
            pattern: '^[a-z0-9]+$',
            title: 'Username',
            examples: ['userson']
        },
        phone: {
            type: 'string',
            title: 'Phone',
            examples: ['+998901234567']
        },
        profile_image_url: {
            type: 'string',
            title: 'Profile Image Url'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        }
    },
    type: 'object',
    required: ['id', 'first_name', 'last_name', 'username', 'phone', 'profile_image_url', 'is_active', 'is_superuser'],
    title: 'UserRead'
} as const;

export const UserUpdateSchema = {
    properties: {
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name',
            examples: ['Aziz']
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name',
            examples: ['Karimov']
        },
        middle_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Middle Name',
            examples: ['Toshmatovich']
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20,
                    minLength: 2,
                    pattern: '^[a-z0-9]+$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username',
            examples: ['userberg']
        },
        profile_image_url: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(https?|ftp)://[^\\s/$.?#].[^\\s]*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Image Url',
            examples: ['https://www.profileimageurl.com']
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        confirm_password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Confirm Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;