// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Yangi tekshiruv yaratish
 */
export type ExaminationCreate = {
    /**
     * Bemor ID
     */
    patient_id: number;
    /**
     * Tekshiruv sanasi
     */
    examination_date?: string;
    /**
     * Shablon turi
     */
    template_type: string;
    /**
     * Tekshiruv ma'lumotlari (JSONB)
     */
    examination_data?: {
        [key: string]: unknown;
    };
    /**
     * Xulosa / ЗАКЛЮЧЕНИЕ
     */
    conclusion?: (string | null);
    /**
     * Tavsiyalar / РЕКОМЕНДАЦИИ
     */
    recommendations?: (string | null);
    /**
     * Ichki izohlar
     */
    notes?: (string | null);
    /**
     * Holat
     */
    status?: string;
};

/**
 * Tekshiruvlar ro'yxati
 */
export type ExaminationList = {
    id: number;
    patient_id: number;
    patient_name?: (string | null);
    examination_date: string;
    template_type: string;
    template_name?: (string | null);
    status: string;
    created_at: string;
};

/**
 * Tekshiruv ma'lumotlarini o'qish
 */
export type ExaminationRead = {
    /**
     * Bemor ID
     */
    patient_id: number;
    /**
     * Tekshiruv sanasi
     */
    examination_date?: string;
    /**
     * Shablon turi
     */
    template_type: string;
    /**
     * Tekshiruv ma'lumotlari (JSONB)
     */
    examination_data?: {
        [key: string]: unknown;
    };
    /**
     * Xulosa / ЗАКЛЮЧЕНИЕ
     */
    conclusion?: (string | null);
    /**
     * Tavsiyalar / РЕКОМЕНДАЦИИ
     */
    recommendations?: (string | null);
    /**
     * Ichki izohlar
     */
    notes?: (string | null);
    /**
     * Holat
     */
    status?: string;
    id: number;
    doctor_id: number;
    created_at: string;
    updated_at?: (string | null);
    patient_name?: (string | null);
    doctor_name?: (string | null);
    template_name?: (string | null);
};

/**
 * Tekshiruv ma'lumotlarini yangilash
 */
export type ExaminationUpdate = {
    examination_date?: (string | null);
    examination_data?: ({
    [key: string]: unknown;
} | null);
    conclusion?: (string | null);
    recommendations?: (string | null);
    notes?: (string | null);
    status?: (string | null);
};

export type HealthCheck = {
    status: string;
    environment: string;
    version: string;
    timestamp: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    created_at?: (string | null);
    updated_at?: (string | null);
    title: string;
    description?: (string | null);
    id: number;
    owner_id: number;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Job = {
    id: string;
};

/**
 * Generic message response schema
 */
export type Message = {
    message: string;
};

export type PaginatedResponse = {
    data: Array<UserRead>;
    count: number;
};

/**
 * Yangi bemor yaratish
 */
export type PatientCreate = {
    /**
     * Familiya
     */
    last_name: string;
    /**
     * Ism
     */
    first_name: string;
    /**
     * Otasining ismi / Sharifi
     */
    middle_name?: (string | null);
    /**
     * Tug'ilgan sana
     */
    birth_date?: (string | null);
    /**
     * Jins: male/female
     */
    gender: string;
    /**
     * Telefon raqami
     */
    phone?: (string | null);
    /**
     * Manzil
     */
    address?: (string | null);
    /**
     * Izohlar
     */
    notes?: (string | null);
};

/**
 * Bemorlar ro'yxati
 */
export type PatientList = {
    id: number;
    last_name: string;
    first_name: string;
    middle_name?: (string | null);
    birth_date?: (string | null);
    gender: string;
    phone?: (string | null);
    created_at: string;
    examination_count?: number;
};

/**
 * Bemor ma'lumotlarini o'qish
 */
export type PatientRead = {
    /**
     * Familiya
     */
    last_name: string;
    /**
     * Ism
     */
    first_name: string;
    /**
     * Otasining ismi / Sharifi
     */
    middle_name?: (string | null);
    /**
     * Tug'ilgan sana
     */
    birth_date?: (string | null);
    /**
     * Jins: male/female
     */
    gender: string;
    /**
     * Telefon raqami
     */
    phone?: (string | null);
    /**
     * Manzil
     */
    address?: (string | null);
    /**
     * Izohlar
     */
    notes?: (string | null);
    id: number;
    created_at: string;
    updated_at?: (string | null);
    examination_count?: number;
};

/**
 * Bemor ma'lumotlarini yangilash
 */
export type PatientUpdate = {
    last_name?: (string | null);
    first_name?: (string | null);
    middle_name?: (string | null);
    birth_date?: (string | null);
    gender?: (string | null);
    phone?: (string | null);
    address?: (string | null);
    notes?: (string | null);
};

export type ReadyCheck = {
    status: string;
    environment: string;
    version: string;
    app: string;
    database: string;
    redis: string;
    timestamp: string;
};

export type Token = {
    access_token: string;
    token_type: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    name?: (string | null);
    username?: (string | null);
    phone: string;
    email?: (string | null);
    password: string;
    confirm_password?: (string | null);
    is_superuser?: boolean;
    is_active?: boolean;
};

export type UserRead = {
    id: string;
    full_name: string;
    username: string;
    phone: string;
    email?: (string | null);
    profile_image_url: string;
    is_active: boolean;
    is_superuser: boolean;
};

export type UserUpdate = {
    name?: (string | null);
    username?: (string | null);
    email?: (string | null);
    profile_image_url?: (string | null);
    password?: (string | null);
    confirm_password?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetExaminationsApiV1ExaminationsGetData = {
    /**
     * Boshlanish sanasi
     */
    dateFrom?: (string | null);
    /**
     * Tugash sanasi
     */
    dateTo?: (string | null);
    page?: number;
    /**
     * Bemor ID
     */
    patientId?: (number | null);
    perPage?: number;
    status?: (string | null);
    /**
     * Shablon turi
     */
    templateType?: (string | null);
};

export type GetExaminationsApiV1ExaminationsGetResponse = ({
    [key: string]: unknown;
});

export type CreateExaminationApiV1ExaminationsPostData = {
    requestBody: ExaminationCreate;
};

export type CreateExaminationApiV1ExaminationsPostResponse = (ExaminationRead);

export type GetRecentExaminationsApiV1ExaminationsRecentGetData = {
    limit?: number;
};

export type GetRecentExaminationsApiV1ExaminationsRecentGetResponse = (Array<ExaminationList>);

export type GetStatisticsApiV1ExaminationsStatisticsGetData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
};

export type GetStatisticsApiV1ExaminationsStatisticsGetResponse = ({
    [key: string]: unknown;
});

export type GetTemplateTypesApiV1ExaminationsTemplatesGetResponse = ({
    [key: string]: unknown;
});

export type GetExaminationApiV1ExaminationsExaminationIdGetData = {
    examinationId: number;
};

export type GetExaminationApiV1ExaminationsExaminationIdGetResponse = (ExaminationRead);

export type UpdateExaminationApiV1ExaminationsExaminationIdPutData = {
    examinationId: number;
    requestBody: ExaminationUpdate;
};

export type UpdateExaminationApiV1ExaminationsExaminationIdPutResponse = (ExaminationRead);

export type DeleteExaminationApiV1ExaminationsExaminationIdDeleteData = {
    examinationId: number;
};

export type DeleteExaminationApiV1ExaminationsExaminationIdDeleteResponse = (Message);

export type UpdateExaminationStatusApiV1ExaminationsExaminationIdStatusPatchData = {
    examinationId: number;
    status: string;
};

export type UpdateExaminationStatusApiV1ExaminationsExaminationIdStatusPatchResponse = (unknown);

export type GetExaminationForPrintApiV1ExaminationsExaminationIdPrintGetData = {
    examinationId: number;
};

export type GetExaminationForPrintApiV1ExaminationsExaminationIdPrintGetResponse = ({
    [key: string]: unknown;
});

export type HealthApiV1HealthGetResponse = (HealthCheck);

export type ReadyApiV1ReadyGetResponse = (ReadyCheck);

export type ReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ReadItemsResponse = (ItemsPublic);

export type CreateItemData = {
    requestBody: ItemCreate;
};

export type CreateItemResponse = (ItemPublic);

export type ReadItemData = {
    id: number;
};

export type ReadItemResponse = (ItemPublic);

export type UpdateItemData = {
    id: number;
    requestBody: ItemUpdate;
};

export type UpdateItemResponse = (ItemPublic);

export type DeleteItemData = {
    id: number;
};

export type DeleteItemResponse = (Message);

export type LoginAccessTokenData = {
    formData: Body_login_access_token;
};

export type LoginAccessTokenResponse = (Token);

export type RefreshAccessTokenResponse = ({
    [key: string]: (string);
});

export type LogoutApiV1LogoutPostData = {
    refreshToken?: (string | null);
};

export type LogoutApiV1LogoutPostResponse = ({
    [key: string]: (string);
});

export type GetPatientsApiV1PatientsGetData = {
    gender?: (string | null);
    page?: number;
    perPage?: number;
    /**
     * Qidiruv so'zi
     */
    query?: (string | null);
};

export type GetPatientsApiV1PatientsGetResponse = ({
    [key: string]: unknown;
});

export type CreatePatientApiV1PatientsPostData = {
    requestBody: PatientCreate;
};

export type CreatePatientApiV1PatientsPostResponse = (PatientRead);

export type GetRecentPatientsApiV1PatientsRecentGetData = {
    limit?: number;
};

export type GetRecentPatientsApiV1PatientsRecentGetResponse = (Array<PatientList>);

export type GetPatientApiV1PatientsPatientIdGetData = {
    patientId: number;
};

export type GetPatientApiV1PatientsPatientIdGetResponse = (PatientRead);

export type UpdatePatientApiV1PatientsPatientIdPutData = {
    patientId: number;
    requestBody: PatientUpdate;
};

export type UpdatePatientApiV1PatientsPatientIdPutResponse = (PatientRead);

export type DeletePatientApiV1PatientsPatientIdDeleteData = {
    patientId: number;
};

export type DeletePatientApiV1PatientsPatientIdDeleteResponse = (Message);

export type CreateTaskApiV1TasksTaskPostData = {
    message: string;
};

export type CreateTaskApiV1TasksTaskPostResponse = (Job);

export type GetTaskApiV1TasksTaskTaskIdGetData = {
    taskId: string;
};

export type GetTaskApiV1TasksTaskTaskIdGetResponse = (({
    [key: string]: unknown;
} | null));

export type CreateUserData = {
    requestBody: UserCreate;
};

export type CreateUserResponse = (UserRead);

export type ReadUsersData = {
    limit?: number;
    skip?: number;
};

export type ReadUsersResponse = (PaginatedResponse);

export type ReadUserMeResponse = (UserRead);

export type DeleteUserMeResponse = ({
    [key: string]: (string);
});

export type UpdateUserMeData = {
    requestBody: UserUpdate;
};

export type UpdateUserMeResponse = (UserRead);

export type UpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UpdatePasswordMeResponse = ({
    [key: string]: (string);
});

export type ReadUserByIdData = {
    userId: number;
};

export type ReadUserByIdResponse = (UserRead);

export type UpdateUserData = {
    requestBody: UserUpdate;
    userId: number;
};

export type UpdateUserResponse = (UserRead);

export type DeleteUserData = {
    userId: number;
};

export type DeleteUserResponse = ({
    [key: string]: (string);
});

export type DeleteDbUserData = {
    username: string;
};

export type DeleteDbUserResponse = ({
    [key: string]: (string);
});